#############################################################################
# Makefile for building: build_u32/UDM-600
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon May 4 18:11:26 2020
# Project:  sensor_control.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.7/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++ CONFIG+=debug -o Makefile sensor_control.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_TTY_POSIX_ -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.7/include/QtCore -I/usr/local/Trolltech/Qt-4.8.7/include/QtGui -I/usr/local/Trolltech/Qt-4.8.7/include -Iext_h/qwt -Isrc_project_independent -Isrc_3rd_party/qextserialport -Ibuild_u32/moc
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.7/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.7/lib ext_lib/u32/libqwt.a -lQtGui -L/usr/local/Trolltech/Qt-4.8.7/lib -L/usr/X11R6/lib -lXrender -lfontconfig -lfreetype -lXext -lX11 -lQtCore -lz -lm -ldl -lrt -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.7/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build_u32/obj/

####### Files

SOURCES       = src/view_connect.cpp \
		src/main.cpp \
		src/view_calibration_machine.cpp \
		src/mainwindow.cpp \
		src/view_diagram.cpp \
		src_3rd_party/qextserialport/qextserialport.cpp \
		src_3rd_party/qextserialport/qextserialenumerator_unix.cpp \
		src_3rd_party/qextserialport/posix_qextserialport.cpp \
		src_project_independent/linear_converter_f.c \
		src_project_independent/calibration_structure.cpp \
		src/ctrl_tenso.cpp \
		src_project_independent/serial_frame3_parser.cpp \
		src_project_independent/data_storage.cpp \
		src_project_independent/view_calibration_structure.cpp \
		src_project_independent/view_config_serial_connect.cpp \
		src_project_independent/crc_16.c \
		src_project_independent/serial_frame3.c \
		src_project_independent/qwt_plot_diagram.cpp \
		src_project_independent/fir_filter.cpp build_u32/moc/moc_view_calibration_machine.cpp \
		build_u32/moc/moc_view_connect.cpp \
		build_u32/moc/moc_mainwindow.cpp \
		build_u32/moc/moc_view_diagram.cpp \
		build_u32/moc/moc_qextserialport.cpp \
		build_u32/moc/moc_qextserialenumerator.cpp \
		build_u32/moc/moc_view_config_serial_connect.cpp \
		build_u32/moc/moc_view_calibration_structure.cpp \
		build_u32/moc/moc_data_storage.cpp \
		build_u32/moc/moc_calibration_structure.cpp \
		build_u32/moc/moc_ctrl_tenso.cpp \
		build_u32/moc/moc_serial_frame3_parser.cpp \
		build_u32/moc/moc_qwt_plot_diagram.cpp \
		build_u32/moc/moc_fir_filter.cpp
OBJECTS       = build_u32/obj/view_connect.o \
		build_u32/obj/main.o \
		build_u32/obj/view_calibration_machine.o \
		build_u32/obj/mainwindow.o \
		build_u32/obj/view_diagram.o \
		build_u32/obj/qextserialport.o \
		build_u32/obj/qextserialenumerator_unix.o \
		build_u32/obj/posix_qextserialport.o \
		build_u32/obj/linear_converter_f.o \
		build_u32/obj/calibration_structure.o \
		build_u32/obj/ctrl_tenso.o \
		build_u32/obj/serial_frame3_parser.o \
		build_u32/obj/data_storage.o \
		build_u32/obj/view_calibration_structure.o \
		build_u32/obj/view_config_serial_connect.o \
		build_u32/obj/crc_16.o \
		build_u32/obj/serial_frame3.o \
		build_u32/obj/qwt_plot_diagram.o \
		build_u32/obj/fir_filter.o \
		build_u32/obj/moc_view_calibration_machine.o \
		build_u32/obj/moc_view_connect.o \
		build_u32/obj/moc_mainwindow.o \
		build_u32/obj/moc_view_diagram.o \
		build_u32/obj/moc_qextserialport.o \
		build_u32/obj/moc_qextserialenumerator.o \
		build_u32/obj/moc_view_config_serial_connect.o \
		build_u32/obj/moc_view_calibration_structure.o \
		build_u32/obj/moc_data_storage.o \
		build_u32/obj/moc_calibration_structure.o \
		build_u32/obj/moc_ctrl_tenso.o \
		build_u32/obj/moc_serial_frame3_parser.o \
		build_u32/obj/moc_qwt_plot_diagram.o \
		build_u32/obj/moc_fir_filter.o
DIST          = /usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/static.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf \
		sensor_control.pro
QMAKE_TARGET  = UDM-600
DESTDIR       = build_u32/
TARGET        = build_u32/UDM-600

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) build_u32/ || $(MKDIR) build_u32/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sensor_control.pro  /usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/static.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.7/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.7/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++ CONFIG+=debug -o Makefile sensor_control.pro
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/static.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.7/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.7/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.7/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.7/mkspecs/linux-g++ CONFIG+=debug -o Makefile sensor_control.pro

dist: 
	@$(CHK_DIR_EXISTS) build_u32/obj/UDM-6001.0.0 || $(MKDIR) build_u32/obj/UDM-6001.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build_u32/obj/UDM-6001.0.0/ && $(COPY_FILE) --parents src/view_calibration_machine.h src/view_connect.h src/tenso_sensor_structure.h src/mainwindow.h src/view_diagram.h src_3rd_party/qextserialport/qextserialport_global.h src_3rd_party/qextserialport/qextserialport.h src_3rd_party/qextserialport/qextserialenumerator.h src_project_independent/view_config_serial_connect.h src_project_independent/view_calibration_structure.h src_project_independent/linear_converter_f.h src_project_independent/data_storage.h src_project_independent/calibration_structure.h src_project_independent/crc_16.h src/ctrl_tenso.h src_project_independent/serial_frame3_parser.h src_project_independent/serial_frame3.h src_project_independent/serial_frame3.h src_project_independent/qwt_plot_diagram.h src_project_independent/fir_filter.h build_u32/obj/UDM-6001.0.0/ && $(COPY_FILE) --parents src/view_connect.cpp src/main.cpp src/view_calibration_machine.cpp src/mainwindow.cpp src/view_diagram.cpp src_3rd_party/qextserialport/qextserialport.cpp src_3rd_party/qextserialport/qextserialenumerator_unix.cpp src_3rd_party/qextserialport/posix_qextserialport.cpp src_project_independent/linear_converter_f.c src_project_independent/calibration_structure.cpp src/ctrl_tenso.cpp src_project_independent/serial_frame3_parser.cpp src_project_independent/data_storage.cpp src_project_independent/view_calibration_structure.cpp src_project_independent/view_config_serial_connect.cpp src_project_independent/crc_16.c src_project_independent/serial_frame3.c src_project_independent/qwt_plot_diagram.cpp src_project_independent/fir_filter.cpp build_u32/obj/UDM-6001.0.0/ && (cd `dirname build_u32/obj/UDM-6001.0.0` && $(TAR) UDM-6001.0.0.tar UDM-6001.0.0 && $(COMPRESS) UDM-6001.0.0.tar) && $(MOVE) `dirname build_u32/obj/UDM-6001.0.0`/UDM-6001.0.0.tar.gz . && $(DEL_FILE) -r build_u32/obj/UDM-6001.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build_u32/moc/moc_view_calibration_machine.cpp build_u32/moc/moc_view_connect.cpp build_u32/moc/moc_mainwindow.cpp build_u32/moc/moc_view_diagram.cpp build_u32/moc/moc_qextserialport.cpp build_u32/moc/moc_qextserialenumerator.cpp build_u32/moc/moc_view_config_serial_connect.cpp build_u32/moc/moc_view_calibration_structure.cpp build_u32/moc/moc_data_storage.cpp build_u32/moc/moc_calibration_structure.cpp build_u32/moc/moc_ctrl_tenso.cpp build_u32/moc/moc_serial_frame3_parser.cpp build_u32/moc/moc_qwt_plot_diagram.cpp build_u32/moc/moc_fir_filter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build_u32/moc/moc_view_calibration_machine.cpp build_u32/moc/moc_view_connect.cpp build_u32/moc/moc_mainwindow.cpp build_u32/moc/moc_view_diagram.cpp build_u32/moc/moc_qextserialport.cpp build_u32/moc/moc_qextserialenumerator.cpp build_u32/moc/moc_view_config_serial_connect.cpp build_u32/moc/moc_view_calibration_structure.cpp build_u32/moc/moc_data_storage.cpp build_u32/moc/moc_calibration_structure.cpp build_u32/moc/moc_ctrl_tenso.cpp build_u32/moc/moc_serial_frame3_parser.cpp build_u32/moc/moc_qwt_plot_diagram.cpp build_u32/moc/moc_fir_filter.cpp
build_u32/moc/moc_view_calibration_machine.cpp: src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src/view_calibration_machine.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/view_calibration_machine.h -o build_u32/moc/moc_view_calibration_machine.cpp

build_u32/moc/moc_view_connect.cpp: src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src/view_connect.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/view_connect.h -o build_u32/moc/moc_view_connect.cpp

build_u32/moc/moc_mainwindow.cpp: src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src/view_connect.h \
		src/view_diagram.h \
		src/view_calibration_machine.h \
		src/mainwindow.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o build_u32/moc/moc_mainwindow.cpp

build_u32/moc/moc_view_diagram.cpp: src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src/view_diagram.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/view_diagram.h -o build_u32/moc/moc_view_diagram.cpp

build_u32/moc/moc_qextserialport.cpp: src_3rd_party/qextserialport/qextserialport_global.h \
		src_3rd_party/qextserialport/qextserialport.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_3rd_party/qextserialport/qextserialport.h -o build_u32/moc/moc_qextserialport.cpp

build_u32/moc/moc_qextserialenumerator.cpp: src_3rd_party/qextserialport/qextserialport_global.h \
		src_3rd_party/qextserialport/qextserialenumerator.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_3rd_party/qextserialport/qextserialenumerator.h -o build_u32/moc/moc_qextserialenumerator.cpp

build_u32/moc/moc_view_config_serial_connect.cpp: src_project_independent/view_config_serial_connect.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/view_config_serial_connect.h -o build_u32/moc/moc_view_config_serial_connect.cpp

build_u32/moc/moc_view_calibration_structure.cpp: src_project_independent/calibration_structure.h \
		src_project_independent/linear_converter_f.h \
		src_project_independent/view_calibration_structure.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/view_calibration_structure.h -o build_u32/moc/moc_view_calibration_structure.cpp

build_u32/moc/moc_data_storage.cpp: src_project_independent/data_storage.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/data_storage.h -o build_u32/moc/moc_data_storage.cpp

build_u32/moc/moc_calibration_structure.cpp: src_project_independent/linear_converter_f.h \
		src_project_independent/calibration_structure.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/calibration_structure.h -o build_u32/moc/moc_calibration_structure.cpp

build_u32/moc/moc_ctrl_tenso.cpp: src/tenso_sensor_structure.h \
		src/ctrl_tenso.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src/ctrl_tenso.h -o build_u32/moc/moc_ctrl_tenso.cpp

build_u32/moc/moc_serial_frame3_parser.cpp: src_project_independent/crc_16.h \
		src_project_independent/serial_frame3.h \
		src_project_independent/serial_frame3_parser.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/serial_frame3_parser.h -o build_u32/moc/moc_serial_frame3_parser.cpp

build_u32/moc/moc_qwt_plot_diagram.cpp: src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src_project_independent/qwt_plot_diagram.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/qwt_plot_diagram.h -o build_u32/moc/moc_qwt_plot_diagram.cpp

build_u32/moc/moc_fir_filter.cpp: src_project_independent/fir_filter.h
	/usr/local/Trolltech/Qt-4.8.7/bin/moc $(DEFINES) $(INCPATH) src_project_independent/fir_filter.h -o build_u32/moc/moc_fir_filter.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build_u32/obj/view_connect.o: src/view_connect.cpp src/view_connect.h \
		src/ctrl_tenso.h \
		src/tenso_sensor_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/view_connect.o src/view_connect.cpp

build_u32/obj/main.o: src/main.cpp src/mainwindow.h \
		src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src/view_connect.h \
		src/view_diagram.h \
		src/view_calibration_machine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/main.o src/main.cpp

build_u32/obj/view_calibration_machine.o: src/view_calibration_machine.cpp src/view_calibration_machine.h \
		src/ctrl_tenso.h \
		src/tenso_sensor_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/view_calibration_machine.o src/view_calibration_machine.cpp

build_u32/obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/ctrl_tenso.h \
		src/tenso_sensor_structure.h \
		src/view_connect.h \
		src/view_diagram.h \
		src/view_calibration_machine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/mainwindow.o src/mainwindow.cpp

build_u32/obj/view_diagram.o: src/view_diagram.cpp src/view_diagram.h \
		src/ctrl_tenso.h \
		src/tenso_sensor_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/view_diagram.o src/view_diagram.cpp

build_u32/obj/qextserialport.o: src_3rd_party/qextserialport/qextserialport.cpp src_3rd_party/qextserialport/qextserialport.h \
		src_3rd_party/qextserialport/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/qextserialport.o src_3rd_party/qextserialport/qextserialport.cpp

build_u32/obj/qextserialenumerator_unix.o: src_3rd_party/qextserialport/qextserialenumerator_unix.cpp src_3rd_party/qextserialport/qextserialenumerator.h \
		src_3rd_party/qextserialport/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/qextserialenumerator_unix.o src_3rd_party/qextserialport/qextserialenumerator_unix.cpp

build_u32/obj/posix_qextserialport.o: src_3rd_party/qextserialport/posix_qextserialport.cpp src_3rd_party/qextserialport/qextserialport.h \
		src_3rd_party/qextserialport/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/posix_qextserialport.o src_3rd_party/qextserialport/posix_qextserialport.cpp

build_u32/obj/linear_converter_f.o: src_project_independent/linear_converter_f.c src_project_independent/linear_converter_f.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build_u32/obj/linear_converter_f.o src_project_independent/linear_converter_f.c

build_u32/obj/calibration_structure.o: src_project_independent/calibration_structure.cpp src_project_independent/calibration_structure.h \
		src_project_independent/linear_converter_f.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/calibration_structure.o src_project_independent/calibration_structure.cpp

build_u32/obj/ctrl_tenso.o: src/ctrl_tenso.cpp src/ctrl_tenso.h \
		src/tenso_sensor_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/ctrl_tenso.o src/ctrl_tenso.cpp

build_u32/obj/serial_frame3_parser.o: src_project_independent/serial_frame3_parser.cpp src_project_independent/serial_frame3_parser.h \
		src_project_independent/crc_16.h \
		src_project_independent/serial_frame3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/serial_frame3_parser.o src_project_independent/serial_frame3_parser.cpp

build_u32/obj/data_storage.o: src_project_independent/data_storage.cpp src_project_independent/data_storage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/data_storage.o src_project_independent/data_storage.cpp

build_u32/obj/view_calibration_structure.o: src_project_independent/view_calibration_structure.cpp src_project_independent/view_calibration_structure.h \
		src_project_independent/calibration_structure.h \
		src_project_independent/linear_converter_f.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/view_calibration_structure.o src_project_independent/view_calibration_structure.cpp

build_u32/obj/view_config_serial_connect.o: src_project_independent/view_config_serial_connect.cpp src_project_independent/view_config_serial_connect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/view_config_serial_connect.o src_project_independent/view_config_serial_connect.cpp

build_u32/obj/crc_16.o: src_project_independent/crc_16.c src_project_independent/crc_16.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build_u32/obj/crc_16.o src_project_independent/crc_16.c

build_u32/obj/serial_frame3.o: src_project_independent/serial_frame3.c src_project_independent/crc_16.h \
		src_project_independent/serial_frame3.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o build_u32/obj/serial_frame3.o src_project_independent/serial_frame3.c

build_u32/obj/qwt_plot_diagram.o: src_project_independent/qwt_plot_diagram.cpp src_project_independent/qwt_plot_diagram.h \
		src/ctrl_tenso.h \
		src/tenso_sensor_structure.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/qwt_plot_diagram.o src_project_independent/qwt_plot_diagram.cpp

build_u32/obj/fir_filter.o: src_project_independent/fir_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/fir_filter.o src_project_independent/fir_filter.cpp

build_u32/obj/moc_view_calibration_machine.o: build_u32/moc/moc_view_calibration_machine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_view_calibration_machine.o build_u32/moc/moc_view_calibration_machine.cpp

build_u32/obj/moc_view_connect.o: build_u32/moc/moc_view_connect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_view_connect.o build_u32/moc/moc_view_connect.cpp

build_u32/obj/moc_mainwindow.o: build_u32/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_mainwindow.o build_u32/moc/moc_mainwindow.cpp

build_u32/obj/moc_view_diagram.o: build_u32/moc/moc_view_diagram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_view_diagram.o build_u32/moc/moc_view_diagram.cpp

build_u32/obj/moc_qextserialport.o: build_u32/moc/moc_qextserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_qextserialport.o build_u32/moc/moc_qextserialport.cpp

build_u32/obj/moc_qextserialenumerator.o: build_u32/moc/moc_qextserialenumerator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_qextserialenumerator.o build_u32/moc/moc_qextserialenumerator.cpp

build_u32/obj/moc_view_config_serial_connect.o: build_u32/moc/moc_view_config_serial_connect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_view_config_serial_connect.o build_u32/moc/moc_view_config_serial_connect.cpp

build_u32/obj/moc_view_calibration_structure.o: build_u32/moc/moc_view_calibration_structure.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_view_calibration_structure.o build_u32/moc/moc_view_calibration_structure.cpp

build_u32/obj/moc_data_storage.o: build_u32/moc/moc_data_storage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_data_storage.o build_u32/moc/moc_data_storage.cpp

build_u32/obj/moc_calibration_structure.o: build_u32/moc/moc_calibration_structure.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_calibration_structure.o build_u32/moc/moc_calibration_structure.cpp

build_u32/obj/moc_ctrl_tenso.o: build_u32/moc/moc_ctrl_tenso.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_ctrl_tenso.o build_u32/moc/moc_ctrl_tenso.cpp

build_u32/obj/moc_serial_frame3_parser.o: build_u32/moc/moc_serial_frame3_parser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_serial_frame3_parser.o build_u32/moc/moc_serial_frame3_parser.cpp

build_u32/obj/moc_qwt_plot_diagram.o: build_u32/moc/moc_qwt_plot_diagram.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_qwt_plot_diagram.o build_u32/moc/moc_qwt_plot_diagram.cpp

build_u32/obj/moc_fir_filter.o: build_u32/moc/moc_fir_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build_u32/obj/moc_fir_filter.o build_u32/moc/moc_fir_filter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

